baseURL = "http://evan.fasullo.com"
languageCode = "en"
title = "Dr. Evan Freedman | Board Certified Forensic Psychologist"
theme = "hugo-initio"

[params]
    name = "Evan Freedman, PhD, ABPP"
    description = "Board Certified Forensic Psychologist"
    email = "evan@drevanfreedman.com"
    phone = "Phone: 360-734-2664"
    fax = "Fax: 360-785-2056"
    address = "1414 Broadway St, Suite G, Bellingham WA 98225"
    year = 2022
    background = ""
    banner = "/images/evan-header.jpg"
    favicon = "/images/gt_favicon.png"
    DateForm = "February 23, 2022"
    author = ""

    cvName = "Curriculum Vitae"
    cvDescription = "Dr. Freedman's CV is available for download."
    cvFile = "/files/CV-EvanFreedman.pdf"

    showSubheader = true

    showFooterContact = true

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Services"
    url = "/#services"
    weight = 3
[[menu.main]]
    name = "Qualifications"
    url = "/#qualifications"
    weight = 5

[params.google.analytics]
    trackerID = "GA-000000000-0"

